linters:
  enable-all: true
  disable:
    - gomnd
    - execinquery
    - exportloopref
    - gochecknoglobals
    - reassign
    - exhaustruct
    - tagliatelle
    - wrapcheck
    - testpackage
    - paralleltest
    - ireturn
    - testifylint
    - err113

linters-settings:
  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: lax
        files:
          - $all
          - "!$test"
        allow:
          - $gostd

  varnamelen:
    min-name-length: 2
    ignore-decls:
      - w http.ResponseWriter
      - r *http.Request
      - r chi.Router

  godot:
    period: false

  mnd:
    ignored-files:
      - '.+_psql.go'
